FROM fholzer/nginx-brotli:latest

# Install required packages
RUN apk add --no-cache openssl curl

# Remove default configs
RUN rm -rf /etc/nginx/conf.d/*

# Create directories
RUN mkdir -p /var/cache/nginx/proxy \
    /var/log/nginx \
    /etc/nginx/ssl \
    /etc/nginx/cloudflare

# Copy nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf
COPY deploy.sh /deploy.sh
# Generate DH parameters
RUN openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048

# Set permissions
RUN chown -R nginx:nginx /var/cache/nginx /var/log/nginx

EXPOSE 80 443

ENTRYPOINT [ "/deploy.sh" ]
CMD ["-g", "daemon off;"]