FROM fholzer/nginx-brotli:latest

# Install openssl
RUN apk add --no-cache openssl

# Remove default nginx config
RUN rm -rf /etc/nginx/conf.d/*

# Copy configurations
COPY nginx.conf /etc/nginx/nginx.conf
COPY ssl/ /etc/nginx/ssl/

# Create necessary directories
RUN mkdir -p /var/cache/nginx/proxy && \
    mkdir -p /var/cache/nginx/fastcgi && \
    mkdir -p /var/log/nginx


# Generate DH parameters 
RUN openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048

# Set permissions
RUN chown -R nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /var/log/nginx && \
    chmod -R 755 /usr/share/nginx/html

EXPOSE 80 443
ENTRYPOINT ["nginx"]
CMD ["-g", "daemon off;"]